### ISSUE TITLE
Support for detecting lanes

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/Fastlane-Plugin#2]
Detect lanes using `fastlane lanes` command and show options to choose lane.

**Comment by KrauseFx** [comment]
I wouldn't use the `fastlane lanes` output, as it might change, however I'm more than happy to provide this information using the JSON format, if that helps :+1:

**Comment by RishabhTayal** [comment]
@KrauseFx That will help a lot.

**Comment by KrauseFx** [comment]
WIP: https://github.com/fastlane/fastlane/pull/1365 :rocket:

**Comment by RishabhTayal** [comment]
Added: https://github.com/RishabhTayal/Fastlane-Plugin/pull/12
